scala_library(
    name='scala',
    dependencies=[
        'contrib/avrohugger/src/3rdparty:avro',
        'contrib/avrohugger/tests/avro',
    ],
    sources=globs('pants/avrohugger/app/Main.scala'),
)
