jvm_binary(
    name = 'tests',
    dependencies = [ 
        'contrib/avrohugger/tests/scala',
        'contrib/avrohugger/tests/avro',
    ],  
    main = 'pants.avrohugger.app.MainApp',
    basename = 'avrohugger-tests',
)

